export {SingUp} from './singup'
export {Login} from './login'
export {Dashboard} from './dashboard'
export {ContacUbic} from './contacto-ubicacion'
export {Product} from './productos'
export {Tasks} from './tasks'
export {Task} from './task-detail'
export {Cart} from './cart'